### PR TITLE
Save dark mode or light mode across all pages on the website

### PR DESCRIPTION
**Pull request by queenkoopa8500**
github pages test for it (So you can see how it works): https://uuphoria2.github.io/sm64coopdx-website/

Test it out here first on the main domain: https://sm64coopdx.com if the color is first dark make it light if its first light then change it to dark. Go on another page and it should reset to dark (Example, the changelog page https://sm64coopdx.com/changelog.html)

https://uuphoria2.github.io/sm64coopdx-website/ if color is first dark again make it light then if its first light then change to dark.
Go on another page like the changelog for example. and it should stay the same setting you wanted which in this case its light Now try reopening and closing it instead of resetting to dark by default on a new tab or closing and opening the website again it should be the same now with this update anytime even if you close and open the website, and even open it in new tabs

### CODE REVIEW

**Comment by queenkoopa8500** [comment]
Or normally on https://sm64coopdx.com/changelog.html if you change the color on that page from dark to light it still goes to the normal default dark color when you go back to the main page. This pull request fixes all the issues for it including this one (changing it on changelog page) Also can be tested here: https://uuphoria2.github.io/sm64coopdx-website/changelog.html

**Comment by queenkoopa8500** [comment]
@Agent-11 Also note that since the test is on github pages that means since main pages go to / it goes to uuphoria2.github.io so on the actual website https://sm64coopdx.com it will work as the actual main page (https://sm64coopdx.com/) is the root (directory /) on there that's why the one I made is only for testing and not deploying it to a real server.

**Comment by queenkoopa8500** [comment]
reopening when im ready

**Comment by uuphoria2** [comment]
@Agent-11 new one at #3

**Comment by queenkoopa8500** [comment]
@Agent-11 new one at #4  :)

**Pull request closed without merging**
